In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../../data/processed/solar_and_daylength_data.csv', index_col = 0)

In [3]:
df.reset_index(inplace = True)

In [4]:
df = df.set_index(pd.to_datetime(df['Date'])).drop('Date', axis = 1)

In [5]:
df = df[['Solar Energy (kWh)', 'Inverter 1 Energy (kWh)', 'Inverter 2 Energy (kWh)', 'Daylength in decimal hours']]

In [6]:
df

,Solar Energy (kWh),Inverter 1 Energy (kWh),Inverter 2 Energy (kWh),Daylength in decimal hours
Date,,,,
2021-11-17,22.8,10.9,11.8,10.33
2021-11-18,22.0,10.6,11.4,10.31
2021-11-19,20.4,9.9,10.5,10.28
2021-11-20,21.3,10.2,11.0,10.26
2021-11-21,22.8,10.8,12.0,10.24
...,...,...,...,...
2022-11-13,0.0,0.0,0.0,10.44
2022-11-14,0.0,0.0,0.0,10.41
2022-11-15,0.0,0.0,0.0,10.39
2022-11-16,0.0,0.0,0.0,10.36
2022-11-17,0.0,0.0,0.0,10.34

In [7]:
df.resample('M').sum()

,Solar Energy (kWh),Inverter 1 Energy (kWh),Inverter 2 Energy (kWh),Daylength in decimal hours
Date,,,,
2021-11-30,299.4,142.5,156.9,142.70
2021-12-31,473.0,196.9,275.8,308.25
2022-01-31,459.1,152.1,307.3,316.96
2022-02-28,880.4,422.0,458.3,308.66
2022-03-31,1298.6,620.2,678.4,372.95
2022-04-30,1451.0,704.1,746.8,392.36
2022-05-31,1620.8,790.5,831.0,432.48
2022-06-30,1536.0,745.7,790.1,431.13
2022-07-31,1411.6,685.9,725.5,437.99
2022-08-31,1254.6,611.2,643.5,413.75
2022-09-30,703.6,531.5,172.1,370.22
2022-10-31,505.5,505.5,0.0,350.17
2022-11-30,57.9,57.9,0.0,179.35

In [8]:
df2 = pd.DataFrame({})
df3 = pd.read_csv('../../data/raw/energy-costs.csv')[1:-1]
start_dates = df3['Billing Period Start'].to_list()
end_dates = df3['Billing Period End'].to_list()
dates = list(zip(start_dates, end_dates))

In [9]:
dates[0]

('11/17/2021', '12/17/2021')

In [10]:
for i in range(len(dates)):
    start_date = dates[i][0].split('/')[2]+'-'+dates[i][0].split('/')[0]+'-'+dates[i][0].split('/')[1]
    end_date = dates[i][1].split('/')[2]+'-'+dates[i][1].split('/')[0]+'-'+dates[i][1].split('/')[1]
    df2 = df2.append(df.loc[start_date:end_date].sum().to_frame().T, ignore_index=True)

/var/folders/5t/3wsbxj9j6s54f2q6y4ydf2kr0000gn/T/ipykernel_57955/3361335731.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(df.loc[start_date:end_date].sum().to_frame().T, ignore_index=True)

In [11]:
df2['Billing Period Start'] = pd.Series(start_dates)
df2['Billing Period End'] = pd.Series(end_dates)

In [12]:
df2

,Solar Energy (kWh),Inverter 1 Energy (kWh),Inverter 2 Energy (kWh),Daylength in decimal hours,Billing Period Start,Billing Period End
0,590.2,282.2,307.8,312.08,11/17/2021,12/17/2021
1,366.8,77.1,289.7,330.72,12/18/2021,1/19/2022
2,738.0,355.5,382.6,298.37,1/20/2022,2/16/2022
3,1280.5,608.4,672.1,384.35,2/17/2022,3/21/2022
4,1323.8,641.0,682.7,369.09,3/22/2022,4/19/2022
5,1511.0,736.2,775.2,395.73,4/20/2022,5/18/2022
6,1546.6,752.0,794.8,428.00,5/19/2022,6/17/2022
7,1594.7,775.0,819.6,457.76,6/18/2022,7/19/2022
8,1123.7,547.8,576.0,384.64,7/20/2022,8/16/2022
9,1108.3,622.9,485.2,434.57,8/17/2022,9/19/2022
10,482.5,482.5,0.0,328.13,9/20/2022,10/17/2022
11,285.4,285.4,0.0,333.53,10/18/2022,11/17/2022

In [13]:
df.loc['2021-11-17':'2021-12-17'].sum()

Solar Energy (kWh)            590.20
Inverter 1 Energy (kWh)       282.20
Inverter 2 Energy (kWh)       307.80
Daylength in decimal hours    312.08
dtype: float64

In [14]:
df4 = df2.merge(df3)
df4

,Solar Energy (kWh),Inverter 1 Energy (kWh),Inverter 2 Energy (kWh),Daylength in decimal hours,Billing Period Start,Billing Period End,Net Usage,Net Generation,Billable kWh,Customer Charge,...,Usage Charge,Subtotal after Adjustments,Non-Renewable Adjustment per kWh,Renewable Adjustment per kWh,Total Adjustment per kWh,Public Benefits Charge per KwH,Public Benefits Charge,California Energy Surcharge per KwH,California Energy Surcharge,Total Charge
0,590.2,282.2,307.8,312.08,11/17/2021,12/17/2021,1262,139,1123,9.6,...,131.28,189.39,0.0218,0.0214,0.0432,0.0285,5.40,0.0003,0.34,195.13
1,366.8,77.1,289.7,330.72,12/18/2021,1/19/2022,2090,44,2046,9.6,...,239.18,337.16,0.0215,0.0217,0.0432,0.0285,9.61,0.0003,0.61,347.39
2,738.0,355.5,382.6,298.37,1/20/2022,2/16/2022,1092,263,829,9.6,...,96.91,142.32,0.0218,0.0214,0.0432,0.0285,4.06,0.0003,0.25,146.63
3,1280.5,608.4,672.1,384.35,2/17/2022,3/21/2022,834,674,160,9.6,...,18.70,35.22,0.0227,0.0205,0.0432,0.0285,1.00,0.0003,0.05,36.27
4,1323.8,641.0,682.7,369.09,3/22/2022,4/19/2022,1068,595,473,9.6,...,55.29,85.33,0.0239,0.0193,0.0432,0.0285,2.43,0.0003,0.14,87.90
5,1511.0,736.2,775.2,395.73,4/20/2022,5/18/2022,1027,675,352,9.6,...,41.15,60.15,0.0086,0.0181,0.0267,0.0285,1.71,0.0003,0.11,61.97
6,1546.6,752.0,794.8,428.00,5/19/2022,6/17/2022,1380,498,882,9.6,...,103.11,129.20,0.0015,0.0172,0.0187,0.0285,3.68,0.0003,0.26,133.15
7,1594.7,775.0,819.6,457.76,6/18/2022,7/19/2022,1808,398,1410,9.6,...,164.83,200.80,0.0028,0.0159,0.0187,0.0285,5.72,0.0003,0.42,206.94
8,1123.7,547.8,576.0,384.64,7/20/2022,8/16/2022,1700,252,1448,9.6,...,169.27,205.95,0.0057,0.0130,0.0187,0.0285,5.87,0.0003,0.43,212.25
9,1108.3,622.9,485.2,434.57,8/17/2022,9/19/2022,1973,318,1655,9.6,...,193.47,252.72,0.0202,0.0098,0.0300,0.0285,7.20,0.0003,0.50,260.42
10,482.5,482.5,0.0,328.13,9/20/2022,10/17/2022,922,265,657,9.6,...,76.80,117.28,0.0403,0.0067,0.0470,0.0285,3.34,0.0003,0.20,120.82
11,285.4,285.4,0.0,333.53,10/18/2022,11/17/2022,1225,110,1115,9.6,...,130.34,193.02,0.0433,0.0043,0.0476,0.0285,5.50,0.0003,0.33,198.85

In [15]:
df4.to_csv('../../data/processed/resampled_merged_data.csv')