In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../../data/processed/solar_and_daylength_data.csv', index_col = 0)

In [3]:
df

,Solar Energy (kWh),Inverter 1 Energy (kWh),Inverter 1 Lifetime Cumulative Energy (kWh),Inverter 2 Energy (kWh),Inverter 2 Lifetime Cumulative Energy (kWh),Daylength in decimal hours
Date,,,,,,
2021-11-17,22.8,10.9,40524.1,11.8,38260.6,10.33
2021-11-18,22.0,10.6,40534.7,11.4,38272.0,10.31
2021-11-19,20.4,9.9,40544.6,10.5,38282.5,10.28
2021-11-20,21.3,10.2,40554.8,11.0,38293.5,10.26
2021-11-21,22.8,10.8,40565.6,12.0,38305.5,10.24
...,...,...,...,...,...,...
2022-11-13,0.0,0.0,46677.9,0.0,44068.8,10.44
2022-11-14,0.0,0.0,46677.9,0.0,44068.8,10.41
2022-11-15,0.0,0.0,46677.9,0.0,44068.8,10.39
2022-11-16,0.0,0.0,46677.9,0.0,44068.8,10.36
2022-11-17,0.0,0.0,46677.9,0.0,44068.8,10.34