In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../../data/interim/combined-sunlight-duration-data.csv', index_col = 0)
df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace = True)

df.loc['2021-11-17':'2022-11-17']

                Sunrise       Sunset    Daylength
Date
2021-11-17  06:21:29 AM  04:41:21 PM  10h 19m 52s
2021-11-18  06:22:25 AM  04:40:52 PM  10h 18m 27s
2021-11-19  06:23:21 AM  04:40:25 PM   10h 17m 4s
2021-11-20  06:24:17 AM  04:39:59 PM  10h 15m 42s
2021-11-21  06:25:12 AM  04:39:35 PM  10h 14m 23s
...                 ...          ...          ...
2022-11-13  06:17:31 AM  04:43:44 PM  10h 26m 13s
2022-11-14  06:18:27 AM  04:43:07 PM  10h 24m 40s
2022-11-15  06:19:23 AM  04:42:33 PM  10h 23m 10s
2022-11-16  06:20:19 AM  04:42:00 PM  10h 21m 41s
2022-11-17  06:21:15 AM  04:41:29 PM  10h 20m 14s

[366 rows x 3 columns]