In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../../data/processed/selected_features.csv', index_col = 0)

In [3]:
df

,Solar Energy (kWh),Inverter 1 Energy (kWh),Inverter 2 Energy (kWh),Daylength in decimal hours,Billing Period Duration,Net Usage,Net Generation,Billable kWh,Usage Charge,Total Adjustment per kWh,Total Charge
0,590.2,282.2,307.8,251.94,30 days,1262,139,1123,131.28,0.0432,195.13
1,366.8,77.1,289.7,266.70,32 days,2090,44,2046,239.18,0.0432,347.39
2,738.0,355.5,382.6,244.05,27 days,1092,263,829,96.91,0.0432,146.63
3,1280.5,608.4,672.1,320.33,32 days,834,674,160,18.70,0.0432,36.27
4,1323.8,641.0,682.7,312.83,28 days,1068,595,473,55.29,0.0432,87.90
5,1511.0,736.2,775.2,339.47,28 days,1027,675,352,41.15,0.0267,61.97
6,1546.6,752.0,794.8,369.80,29 days,1380,498,882,103.11,0.0187,133.15
7,1594.7,775.0,819.6,395.68,31 days,1808,398,1410,164.83,0.0187,206.94
8,1123.7,547.8,576.0,330.32,27 days,1700,252,1448,169.27,0.0187,212.25
9,1108.3,622.9,485.2,368.61,33 days,1973,318,1655,193.47,0.0300,260.42
10,482.5,482.5,0.0,273.81,27 days,922,265,657,76.80,0.0470,120.82
11,285.4,285.4,0.0,273.39,30 days,1225,110,1115,130.34,0.0476,198.85